# Generated by Django 4.0.5 on 2022-06-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_alter_alumno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dia_clase',
            field=models.CharField(max_length=45, verbose_name='Día de Clase'),
        ),
    ]
