# Generated by Django 4.0.5 on 2022-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_alter_curso_dia_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(max_length=45, unique=True, verbose_name='Turno'),
        ),
    ]
