# Generated by Django 4.0.5 on 2022-06-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_alter_turno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rinde',
            name='nota_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota N° 1'),
        ),
        migrations.AlterField(
            model_name='rinde',
            name='nota_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota N° 2'),
        ),
        migrations.AlterField(
            model_name='rinde',
            name='nota_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota N° 3'),
        ),
    ]
