# Generated by Django 4.0.5 on 2022-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_alter_rinde_nota_1_alter_rinde_nota_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiene',
            name='hora_egreso',
            field=models.CharField(max_length=5, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='tiene',
            name='hora_ingreso',
            field=models.CharField(max_length=5, verbose_name='Hora de Entrada'),
        ),
    ]
