# Generated by Django 4.0.5 on 2022-06-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_rinde_cant_inasist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
    ]
