from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('',views.index,name='index'),
    #path('<str:username>/',views.index,name='index'),
    path('register/', views.register, name='register'),
	path('login/', LoginView.as_view(template_name='escuela/login.html'), name='login'),
	path('logout/', LogoutView.as_view(template_name='escuela/logout.html'), name='logout'),
    path('nuevo-tipo-usuario/',views.nuevo_tipo_usuario,name='nuevo_tipo_usuario'),
    #path('nuevo-genero/',views.nuevo_genero,name='nuevo_genero'),
    #path('nueva-persona/',views.nueva_persona,name='nueva_persona'),
    path('nuevo-preceptor/',views.nuevo_preceptor,name='nuevo_preceptor'),
    path('nueva-aula/',views.nueva_aula,name='nueva_aula'),
    path('nuevo-alumno/',views.nuevo_alumno,name='nuevo_alumno'),
    path('nueva-materia/',views.nueva_materia,name='nueva_materia'),
    path('nuevo-curso/',views.nuevo_curso,name='nuevo_curso'),
    path('nuevo-turno/',views.nuevo_turno,name='nuevo_turno'),
    path('nuevo-tiene/',views.nuevo_tiene,name='nuevo_tiene'),
    path('nuevo-rinde/',views.nuevo_rinde,name='nuevo_rinde'),
    path('nuevo-profesor/',views.nuevo_profesor,name='nuevo_profesor'),
    path('nuevo-dicta/',views.nuevo_dicta,name='nuevo_dicta'),
    path('tipos-usuario/',views.listar_tipos_usuario,name='tipos_usuario'),
    path('usuarios/',views.listar_usuarios,name='usuarios'),
    #path('generos/',views.listar_generos,name='generos'),
    #path('personas/',views.listar_personas,name='personas'),
    path('preceptores/',views.listar_preceptores,name='preceptores'),
    path('aulas/',views.listar_aulas,name='aulas'),
    path('alumnos/',views.listar_alumnos,name='alumnos'),
    path('funcionalidades_alumno/',views.funcionalidades_alumno,name='funcionalidades_alumno'),
    path('funcionalidades_profesor/',views.funcionalidades_profesor,name='funcionalidades_profesor'),
    path('funcionalidad_preceptor/',views.funcionalidad_preceptor,name='funcionalidad_preceptor'),
    path('funcionalidades_admin/',views.funcionalidades_admin,name='funcionalidades_admin'),
    path('materias/',views.listar_materias,name='materias'),
    path('cursos/',views.listar_cursos,name='cursos'),
    path('turnos/',views.listar_turnos,name='turnos'),
    path('tienen/',views.listar_tienen,name='tienen'),
    path('rinden/',views.listar_rinden,name='rinden'),
    path('profesores/',views.listar_profesores,name='profesores'),
    path('dictan/',views.listar_dictan,name='dictan'),
    path('modificar-tipo-usuario/<str:pk>', views.modificar_tipo_usuario, name='modificar_tipo_usuario'),
    #path('modificar-usuario/<str:pk>', views.modificar_usuario, name='modificar_usuario'),
    #path('modificar-genero/<str:pk>', views.modificar_genero, name='modificar_genero'),
    #path('modificar-persona/<str:pk>', views.modificar_persona, name='modificar_persona'),
    path('modificar-preceptor/<int:pk>', views.modificar_preceptor, name='modificar_preceptor'),
    path('modificar-aula/<int:pk>', views.modificar_aula, name='modificar_aula'),
    path('modificar-alumno/<int:pk>', views.modificar_alumno, name='modificar_alumno'),
    path('modificar-materia/<int:pk>', views.modificar_materia, name='modificar_materia'),
    path('modificar-curso/<int:pk>', views.modificar_curso, name='modificar_curso'),
    path('modificar-turno/<int:pk>', views.modificar_turno, name='modificar_turno'),
    path('modificar-tiene/<int:pk>', views.modificar_tiene, name='modificar_tiene'),
    path('modificar-rinde/<int:pk>', views.modificar_rinde, name='modificar_rinde'),
    path('modificar-profesor/<int:pk>', views.modificar_profesor, name='modificar_profesor'),
    path('modificar-dicta/<int:pk>', views.modificar_dicta, name='modificar_dicta'),
    path('eliminar-tipo-usuario/<str:pk>', views.eliminar_tipo_usuario, name='eliminar_tipo_usuario'),
    #path('eliminar-usuario/<str:pk>', views.eliminar_usuario, name='eliminar_usuario'),
    #path('eliminar-genero/<str:pk>', views.eliminar_genero, name='eliminar_genero'),
    #path('eliminar-persona/<str:pk>', views.eliminar_persona, name='eliminar_persona'),
    path('eliminar-preceptor/<int:pk>', views.eliminar_preceptor, name='eliminar_preceptor'),
    path('eliminar-aula/<int:pk>', views.eliminar_aula, name='eliminar_aula'),
    path('eliminar-alumno/<int:pk>', views.eliminar_alumno, name='eliminar_alumno'),
    path('eliminar-materia/<int:pk>', views.eliminar_materia, name='eliminar_materia'),
    path('eliminar-curso/<int:pk>', views.eliminar_curso, name='eliminar_curso'),
    path('eliminar-turno/<int:pk>', views.eliminar_turno, name='eliminar_turno'),
    path('eliminar-tiene/<int:pk>', views.eliminar_tiene, name='eliminar_tiene'),
    path('eliminar-rinde/<int:pk>', views.eliminar_rinde, name='eliminar_rinde'),
    path('eliminar-profesor/<int:pk>', views.eliminar_profesor, name='eliminar_profesor'),
    path('eliminar-dicta/<int:pk>', views.eliminar_dicta, name='eliminar_dicta'),
]
